microsoft/playwright-vscode

src/extension.ts

Don't warn when Playwright Test not installed

---

src/playwrightTest.ts
src/utils.ts

I might have complicated the regular expression replace. I've got this one from https://stackoverflow.com/questions/3446170/escape-string-for-use-in-javascript-regex.

Regexp escape paths passed to playwright (#21)

---

src/extension.ts
src/testTree.ts

chore: enhance terminal output logs

---

package.json
src/playwrightTest.ts

chore: enhance debugging experience

---

.github/workflows/node.js.yml
package.json
src/playwrightTest.ts
src/test/runTest.ts
src/test/suites/should-set-environment-variables/extension.test.ts
src/test/suites/should-set-environment-variables/index.ts
test/assets/should-set-environment-variables/.vscode/settings.json
test/assets/should-set-environment-variables/example1.spec.ts
test/assets/should-set-environment-variables/package-lock.json
test/assets/should-set-environment-variables/package.json

feat: add support for setting environment variables

---

src/extension.ts
src/testTree.ts

fix: only add test files to the test explorer

---

src/extension.ts

Fixes #39
---
FYI I didn't test this but it should work.

Adopt status bar item name

---

package.json
src/playwrightTest.ts
src/utils.ts

fix: get PW-Test output data via a file instead stdout

---

src/extension.ts

feat: multi workspace support

---

package.json

Relates https://github.com/microsoft/playwright-vscode/issues/50

chore: auto activate on playwright.config.{ts,js}

---

package.json

This lights up this link on the marketplace

Add bugs entry to package.json

---

src/playwrightTest.ts

fix: project name contains space

---

package.json

Easier to spot different version when its like that.

chore: bump version to 0.1.0

---

package.json
src/extension.ts

fix(#92): activate extension on all commands

---

src/testTree.ts
tests/list-files.spec.ts
tests/list-tests.spec.ts
tests/utils.ts

Fixes https://github.com/microsoft/playwright-vscode/issues/108

fix(workspace): fix multi-folder workspaces

---

src/extension.ts
src/playwrightTest.ts

https://github.com/microsoft/playwright-vscode/issues/114

chore: do not show warnings upon extension activation

---

src/extension.ts
tests/run-tests.spec.ts

Fixes https://github.com/microsoft/playwright-vscode/issues/125

fix(root): allow running test starting from outer folder

---

src/oopReporter.ts
src/playwrightTest.ts
src/reporterServer.ts

Fixes https://github.com/microsoft/playwright-vscode/issues/170, https://github.com/microsoft/playwright-vscode/issues/174, https://github.com/microsoft/playwright-vscode/issues/169

fix(esm): support oop reporter in esm mode

---

src/utils.ts
tests/mock/vscode.ts
tests/run-tests.spec.ts

Fixes https://github.com/microsoft/playwright-vscode/issues/172
Also addresses https://github.com/microsoft/playwright-vscode/pull/171

chore: make highlighting consistent with html reporter

---

src/debugHighlight.ts

Fixes https://github.com/microsoft/playwright-vscode/issues/182
Failing tests are unrelated.

fix: support remote WSL

---

src/installer.ts

Fixes https://github.com/microsoft/playwright/issues/17062

chore: allow picking JS as a language

---

src/extension.ts
src/utils.ts
tests/run-tests.spec.ts

Fixes https://github.com/microsoft/playwright/issues/16991

chore: escape error log html

---

src/debugHighlight.ts
src/playwrightTest.ts
src/reusedBrowser.ts

Fixes https://github.com/microsoft/playwright/issues/16956

chore: don't run driver oop when debugging

---

src/extension.ts
src/reusedBrowser.ts

Fixes https://github.com/microsoft/playwright/issues/17616#event-7489681473

chore: add env from settings to ReusedBrowser

---

src/reusedBrowser.ts

Partial revert of https://github.com/microsoft/playwright-vscode/pull/240.
Relates to https://github.com/microsoft/playwright/issues/18043

fix(recording): do not use sourcesChanged event

---

src/playwrightTest.ts

Change in accordance with https://github.com/microsoft/playwright/issues/17925 (@pavelfeldman).
Fixes https://github.com/microsoft/playwright/issues/17925

Allow user-settings to override NODE_OPTIONS

---

package-lock.json
package.json
src/extension.ts
src/reusedBrowser.ts
tests/auto-close.spec.ts
tests/codegen.spec.ts
tests/mock/vscode.ts
tests/pick-selector.spec.ts
tests/utils.ts

Fixes https://github.com/microsoft/playwright/issues/18048

test: add pick selector, codegen tests

---

README.md
package.json
src/extension.ts
src/reusedBrowser.ts
src/settingsView.ts
tests/codegen.spec.ts

Fixes: https://github.com/microsoft/playwright/issues/17771

chore: use incremental generation in new tests

---

src/playwrightTest.ts

Fixes https://github.com/microsoft/playwright/issues/16957

chore: expose playwright object in browser console while debugging

---

package-lock.json
package.json
src/reusedBrowser.ts

Fixes: https://github.com/microsoft/playwright/issues/18637

chrome: don't hang on page.pause

---

package-lock.json
package.json
src/multimap.ts
src/testTree.ts
tests/list-tests.spec.ts
tests/mock/vscode.ts

Fixes [#18740](https://github.com/microsoft/playwright/issues/18740)

fix: do not override items from different projects

---

src/settingsView.ts

Fixes https://github.com/microsoft/playwright/issues/18874

chore: allow pick locator at all times

---

package-lock.json
package.json

The rest.
Went through the change logs to make sure we are golden.

chore: update major deps updates

---

package-lock.json
package.json
src/extension.ts

Fixes https://github.com/microsoft/playwright/issues/19300

chore: coalescing test listing

---

package-lock.json
package.json
src/utils.ts

Fixes: https://github.com/microsoft/playwright/issues/18954

chore: bring back which retry since it env is not immediately available

---

src/extension.ts
src/oopReporter.ts
src/testTree.ts
tests/debug-tests.spec.ts
tests/list-tests.spec.ts
tests/mock/vscode.ts
tests/run-annotations.spec.ts
tests/run-tests.spec.ts
tests/source-map.spec.ts

Fixes: https://github.com/microsoft/playwright/issues/19279

fix(param): use full test title in the test item id

---

playwright.config.ts
src/playwrightTest.ts

References https://github.com/microsoft/playwright/issues/19746.

fix: pass --headed when reusing browser

---

src/debugHighlight.ts
src/extension.ts
tests/global-errors.spec.ts

Fixes https://github.com/microsoft/playwright/issues/19965

chore: render errors in global setup

---

src/debugHighlight.ts

Fixes https://github.com/microsoft/playwright/issues/20296

chore: escape debug expressions for session evaluate

---

src/reusedBrowser.ts
tests/mock/vscode.ts

Fixes https://github.com/microsoft/playwright-vscode/pull/302
Fixes https://github.com/microsoft/playwright/issues/20661

chore: fix the action rewrite on update

---

src/extension.ts
tests/mock/vscode.ts

This allows us to create our own test request, and also produce test output.

fix(output): wait 500ms before starting the test run

---

package-lock.json
package.json
src/extension.ts

https://github.com/microsoft/playwright/issues/21465

chore: bump min Playwright version

---

src/playwrightTest.ts
tests/run-tests.spec.ts

fix(reuse): ensure workers=1 when running in reuse mode

---

src/playwrightTest.ts

https://github.com/microsoft/playwright/issues/23244#issuecomment-1564824532

chore: gate dog fooding condition better

---

src/playwrightTest.ts
tests/list-files.spec.ts

References https://github.com/microsoft/playwright/issues/23542.

fix(list-files): account for possible errors

---

src/extension.ts

chore: better rewritten 'missing browsers' error message

---

src/installer.ts

Fixes https://github.com/microsoft/playwright/issues/23909

fix(install): do not install browsers if none are selected

---

src/extension.ts

References https://github.com/microsoft/playwright/issues/24342

fix: handle test deselection

---

package-lock.json
package.json
src/reusedBrowser.ts

Fixes https://github.com/microsoft/playwright/issues/24491

chore: do not show can not close message

---

.github/workflows/publish.yml
package-lock.json
package.json

This was a warning on "npm ci" that its deprecated now.

chore: vsce -> @vscode/vsce

---

src/settingsView.ts

Fixes https://github.com/microsoft/playwright/issues/26471

chore: add title for show browser checkbox

---

src/extension.ts
tests/settings.spec.ts

Fixes https://github.com/microsoft/playwright/issues/27252.

feat: stringify non-string values in `playwright.env` setting

---

src/settingsModel.ts
tests/list-tests.spec.ts
tests/mock/vscode.ts

Fixes https://github.com/microsoft/playwright/issues/27171.

fix: when updating settings, update both workspace and global

---

package-lock.json
package.json

Seems like a good time to release a new version.
Diff: https://github.com/microsoft/playwright-vscode/compare/v1.0.16...main

chore: mark v1.0.17

---

package.nls.zh-CN.json

Fixes https://github.com/microsoft/playwright/issues/27905

fix: 'extension.install' command in Chinese

---

src/installer.ts

Motivation: User on Discord wondered why nothing happens.

fix(install): show error when installing in window without workspace

---

src/playwrightTest.ts

Fixes https://github.com/microsoft/playwright/issues/28371

fix(colors): pass the correct force color env

---

src/playwrightTest.ts
src/reusedBrowser.ts
src/traceViewer.ts
src/utils.ts

Relates https://github.com/microsoft/playwright/issues/28703

fix: evaluate 'which' via shell if Node.js is not in PATH (fallback)

---

src/extension.ts

https://github.com/microsoft/playwright/issues/28874

chore: watch .env files (and then reload)

---

src/extension.ts
src/listTests.d.ts
src/playwrightTest.ts
src/testModel.ts
tests/list-files.spec.ts
tests/mock/vscode.ts

Follows up on https://github.com/microsoft/playwright-vscode/pull/346
Relates https://github.com/microsoft/playwright/issues/28703

fix: report config file errors to the user

---

package-lock.json
package.json
tests-integration/globalSetup.ts
tests-integration/package-lock.json
tests-integration/package.json

Drive-by: @vscode/test-electron bump

chore: bump @playwright/test to 1.41.0-beta-1705101589000

---

src/playwrightTest.ts
src/reusedBrowser.ts
src/traceViewer.ts
src/utils.ts

Fixes https://github.com/microsoft/playwright-vscode/pull/406
Relates https://github.com/microsoft/playwright-vscode/pull/406#issuecomment-1894043347

fix: use workspace folder as cwd for finding Node.js

---

l10n/bundle.l10n.fr.json
l10n/bundle.l10n.json
l10n/bundle.l10n.zh-CN.json
src/settingsView.ts

i18n and translate strings for the first settings list.

Fix untranslated l10n

---

src/extension.ts
src/testTree.ts
src/upstream/testTree.ts
tests/mock/vscode.ts

Fixes https://github.com/microsoft/playwright/issues/29938
Relates https://github.com/microsoft/vscode/issues/207877

feat: allow filtering for native VSCode Testing API tags

---

media/settingsView.css
src/extension.ts
src/settingsView.ts
src/testModel.ts

chore: sidebar polish

---

src/workspaceObserver.ts

Fixes https://github.com/microsoft/playwright/issues/30943

chore: dispose event handlers when disposing file watchers

---

src/extension.ts
src/testModel.ts
src/workspaceObserver.ts
tests/list-tests.spec.ts

tests is a drive-by for another issue

chore: take it easy on the watchers, add/remove incrementally

---

package-lock.json
package.json
tests/project-setup.spec.ts

Fixes https://github.com/microsoft/playwright/issues/30936

test: add test to ensure project order

---

src/upstream/teleReceiver.ts
src/upstream/testServerInterface.ts

Fixes https://github.com/microsoft/playwright/issues/31800

chore: allow empty string in regex patterns

---

src/extension.ts
src/vscodeTypes.ts
tests/mock/vscode.ts
tests/utils.ts

See https://github.com/microsoft/playwright-vscode/pull/483#discussion_r1657638327
Refs: #483

test(trace-viewer): testing harness for webview panels

---

l10n/bundle.l10n.de.json
l10n/bundle.l10n.fr.json
l10n/bundle.l10n.json
l10n/bundle.l10n.zh-CN.json
src/reusedBrowser.ts
src/settingsView.ts
src/traceViewer.ts
src/utils.ts

Small refactoring in l10n version message.
getNonce moved into util.ts, as it will be needed later.
See: https://github.com/microsoft/playwright-vscode/pull/483#discussion_r1688989537

l10n and getNonce refactoring

---

.azure-pipelines/publish.yml
PlaywrightVSCode.signproj
package-lock.json
package.json

Docs: https://aka.ms/vsm-ms-publisher-sign
Relates https://github.com/microsoft/playwright/issues/31947

devops: add extension signing using Microbuild

---

src/extension.ts
src/utils.ts
tests/auto-close.spec.ts
tests/debug-tests.spec.ts
tests/embedded-trace-viewer-legacy.spec.ts
tests/mock/vscode.ts
tests/problems.spec.ts
tests/trace-viewer.spec.ts
tests/utils.ts
tsconfig.json

Fixes https://github.com/microsoft/playwright/issues/33531

chore: strip ansi from load errors

---

src/testModel.ts
tests/run-tests.spec.ts

This reverts commit 002fc12e3b2902fd6323ca9ff08a8e6a7c91667b.
Fixes https://github.com/microsoft/playwright/issues/33611

Revert "fix: allow trace in showBrowser mode (#542)"

---

tests/highlight-locators.spec.ts

Fixes https://github.com/microsoft/playwright/issues/33655

chore: fix the highlighter race in test

---

src/extension.ts

Fixes https://github.com/microsoft/playwright/issues/32338
See https://github.com/microsoft/playwright/issues/32338#issuecomment-2495555514 for more information.

fix: consistently enable first config

---

src/settingsView.ts
tests/settings.spec.ts

Reverts microsoft/playwright-vscode#569

Revert "feat: Select all projects checkbox"

---

src/testModel.ts

Fixes https://github.com/microsoft/playwright/issues/34336

fix: respect headless property from the config

---

media/common.css
src/settingsView.script.ts
src/settingsView.ts
src/testTree.ts
tests/list-files.spec.ts
tests/list-tests.spec.ts
tests/mock/vscode.ts
tests/project-setup.spec.ts
tests/project-tree.spec.ts

chore: show disabled projects in the tree

---

l10n/bundle.l10n.de.json
l10n/bundle.l10n.fr.json
l10n/bundle.l10n.it.json
l10n/bundle.l10n.json
l10n/bundle.l10n.zh-CN.json
media/common.css
src/settingsView.ts

chore: show "one worker" next to show browser

---

src/extension.ts
tests/decorations.spec.ts

As per feedback over here: https://github.com/microsoft/playwright-vscode/pull/598#issuecomment-2638210465

feat: decorate line with number of executions

---

package-lock.json
package.json
src/extension.ts
src/playwrightTestTypes.ts
src/testModel.ts
tests/mock/vscode.ts
tests/run-tests.spec.ts

Reverts microsoft/playwright-vscode#610

Revert "feat: provide page snapshot as context to copilot"

---

src/reusedBrowser.ts
tests/pick-selector.spec.ts

Fixes https://github.com/microsoft/playwright/issues/35241.

fix(pick locator): make sure in-page toolbar disappear upon disengage

---

package-lock.json

Fixes "2 vulnerabilities (1 moderate, 1 high)"

chore: bump tar-fs and babel deps

---

tests/debug-tests.spec.ts
tests/global-errors.spec.ts
tests/list-files.spec.ts
tests/list-tests.spec.ts
tests/run-tests.spec.ts
tests/track-configs.spec.ts
tests/utils.ts
tests/watch.spec.ts

In preparation for enabling no-floating-promises in this repository.

test: minor test fixes

---

media/common.css
src/extension.ts
src/settingsView.script.ts
src/settingsView.ts
src/testModel.ts
src/testTree.ts
tests/mock/vscode.ts
tests/track-configs.spec.ts

https://github.com/user-attachments/assets/ab2c07f8-89a6-419c-b028-c740312193cc

chore: show config loading error in test tree

---

package-lock.json
package.json
src/extension.ts

This started failing after https://github.com/microsoft/playwright/pull/36000.

chore: roll to latest Playwright (may 23)

---

package-lock.json
package.json
src/extension.ts
tests/run-tests.spec.ts

chore: roll playwright to new error context

---

src/playwrightTestServer.ts
src/upstream/testServerInterface.ts

See https://github.com/microsoft/playwright/pull/37294, part of https://github.com/microsoft/playwright/issues/37275.

chore: set 0 timeout in debug mode
