microsoft/playwright-vscode

src/playwrightTest.ts
Fixes https://github.com/microsoft/playwright-vscode/issues/93
=> fix(npm6): resolve core relative to @ptw

src/playwrightTest.ts
Fixes https://github.com/microsoft/playwright-vscode/issues/100
Does not yet make debugging work - changes to playwright itself are necessary there. See https://github.com/microsoft/playwright/pull/12250.
=> fix(electron): allow running electron tests

src/installer.ts
We should always enable GitHub Actions by default, and install the linux dependencies as well. Both either breaks the user story/flow or makes the browsers not launchable.
=> chore: have better defaults during install

package-lock.json, package.json, src/playwrightTest.ts, src/utils.ts, tests/mock/vscode.ts
It seems popular, maintained and better than spawning a subprocess see [here](https://www.npmjs.com/package/which).
This fixes the flaky tests too.
=> chore: use in process 'which' instead of spawning sub process

src/installer.ts
Fixes https://github.com/microsoft/playwright-vscode/issues/220
Tested via ` docker run -it node:14 /bin/bash `.
=> chore: make Playwright install work on NPM 6

src/extension.ts
There is no reason to scan node_modules in the workspace and then ignore files. This also allows the extension to work when your workspace folder path includes node_modules.
=> fix: do not scan node_modules

.github/workflows/ci.yml, .github/workflows/publish.yml
This should clear the warnings from here: https://github.com/microsoft/playwright-vscode/actions/runs/3240556841
The remaining one is caused by https://github.com/actions/setup-node/issues/589.
=> chore: upgrade GitHub Action actions

src/installer.ts
`Install Playwright Browser` command currently fails when choosing to include linux dependencies.
```
$ npx playwright install-with-deps chromium firefox webkit
error: unknown command 'install-with-deps'
```
PR updated the command to call use `install --with-deps` which is the correct command for (at least) 1.19+
=> Fix Install Playwright Browser with deps command

src/reusedBrowser.ts, tests/run-tests.spec.ts
"Show browser" mode forces context reuse that survives over multiple test runs. Playwright Test sets up `tracesDir` inside the `test-results` folder, so it will be removed between runs. When context is reused, its ongoing tracing will fail with ENOENT because trace files were suddenly removed. So we disable tracing in this case.
Fixes #21993.
=> fix(reuse): disable tracing

src/playwrightTest.ts, tests/run-tests.spec.ts
Running with `repeat-each=5`, this is not flaky, except for a single test.
=> chore: do not force workers=1 when under test

media/settingsView.css
The issue is that customers often click on the text next to the label, which has `cursor: pointer`, so they think it will open codegen, but in reality, this is not doing anything, because there is no click handler attached.
This is the issue which a bunch of our lab users encountered during the demo at MSBuild.
=> fix: allow settings action clicks next to label

media/settingsView.css
Thats how it was before (green = padding):
Issue was that the horizontal scrollbar was always shown.
=> fix: horizontal scrolling in webview

src/utils.ts
Turns out `which('node')` throws if there is no entry and we expect it to be falsy. This will break users whom's Node.js env gets set lazily.
Full stack without retries:
```
Error: not found: node
at getNotFoundError (/Users/maxschmitt/Developer/playwright-vscode/node_modules/which/lib/index.js:16:17)
at which2 (/Users/maxschmitt/Developer/playwright-vscode/node_modules/which/lib/index.js:76:9)
at async findNode (/Users/maxschmitt/Developer/playwright-vscode/src/utils.ts:145:14)
at async PlaywrightTest._runNode (/Users/maxschmitt/Developer/playwright-vscode/src/playwrightTest.ts:273:29)
at async PlaywrightTest.getPlaywrightInfo (/Users/maxschmitt/Developer/playwright-vscode/src/playwrightTest.ts:69:23)
at async Extension._rebuildModel …
```
=> fix: Node.js is not in PATH and didn't retry

src/reusedBrowser.ts, src/traceViewer.ts, tests/mock/vscode.ts
as per https://code.visualstudio.com/api/advanced-topics/remote-extensions
```ts
// VS Code will return undefined for remoteName if working with a local workspace
if (typeof vscode.env.remoteName === 'undefined') {
vscode.window.showInformationMessage('Not currently connected to a remote workspace.');
}
```
=> fix: detect remote vscode environments correctly

src/reusedBrowser.ts
Partial revert of https://github.com/microsoft/playwright-vscode/commit/d6881ef874f94f499a2be8f70e2d978e0babc847
For future reference:
We keep the remoteName check in our trace viewer decision logic.
Fixes https://github.com/microsoft/playwright/issues/24254
=> fix: show browser always in non-web mode

src/reusedBrowser.ts
Fixes https://github.com/microsoft/playwright/issues/26358
Tested with this: https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/desktop-lite.md#desktop-lightweight-install-script
and that config:
```json
{
"name": "Playwright jammy",
"image": "mcr.microsoft.com/playwright:next-jammy",
"remoteUser": "root",
"runArgs": [
"--privileged",
"--init",
"--shm-size=1g",
"-v",
"/var/run/docker.sock:/var/run/docker.sock"
],
"features": {
"desktop-lite": {
"password": "vscode",
"webPort": "6080",
"vncPort": "5901"
}
}
}
```
=> fix: show browser when DISPLAY env var is provided

src/debugHighlight.ts, tests/highlight-locators.spec.ts, tests/mock/vscode.ts
Fixes https://github.com/microsoft/playwright/issues/27036
Adding a test was more involved than I thought. We already have some logic in place to connect to an existing "ReusableBrowser" but the issue is that `waitForPage` calls `_newContextForReuse` which will reset it, and I want to keep the old content. https://github.com/microsoft/playwright-vscode/blob/ba3258a4a23b0391596fe21164b46c2ad9061d8e/tests/utils.ts#L71-L87
I went a different route over CDP instead.
=> fix: best-effort support for POMs when highlighting

package-lock.json, package.json, src/debugTransform.ts
Fixes https://github.com/microsoft/playwright-vscode/pull/384
Most likely caused by https://github.com/DefinitelyTyped/DefinitelyTyped/commit/5c92dccdca106bc8a45140d84e9f0ff7155393fc.
=> chore: update @babel dependencies

src/methodNames.ts
This regressed in https://github.com/microsoft/playwright-vscode/commit/59f828d54ffa6e8a06620bdb894009d35b500279.
Fixes https://github.com/microsoft/playwright/issues/28437.
=> fix: double fills while debugging

l10n/bundle.l10n.fr.json, package.nls.fr.json
Translations for French
Language code is simply `fr`, as I believe it is standard French and there are no needs for region-specific language (belgium, swiss, french canada, ...)
=> French localization

src/extension.ts, src/playwrightTest.ts, src/utils.ts
https://github.com/microsoft/playwright/issues/28703
Looks like that now in DevTools AND gets surfaced in VSCode as a warning.
=> chore: show more debug info when no Node.js is available

src/playwrightTest.ts
https://github.com/microsoft/playwright/issues/29211
=> fix: find experimental-ct-core cli as a fallback

src/extension.ts, tests/profile-discovery.spec.ts
https://github.com/microsoft/playwright/issues/29367
As per https://code.visualstudio.com/updates/v1_86#_finalized-testrunprofileisdefaultondidchangedefault-apis-for-extension-authors.
=> fix: only mark first project as default

package-lock.json, package.json
This internally was throwing this before (ignored via silent catch()):
```
Error: UNC host 'cpc-maxsc-heqga' access is not allowed
at stat (C:\Users\maxschmitt\Developer\playwright-vscode\lib\fs.js:1597:10)
at Object.stat (C:\Users\maxschmitt\Developer\playwright-vscode\lib\electron\js2c\node_init.js:2:4911)
at isexe (c:\Users\maxschmitt\Developer\playwright-vscode\node_modules\isexe\windows.js:35:6)
at isexe (c:\Users\maxschmitt\Developer\playwright-vscode\node_modules\isexe\index.js:34:3)
at c:\Users\maxschmitt\Developer\playwright-vscode\node_modules\isexe\index.js:24:7
at new Promise (<anonymous>)
at isexe (c:\Users\maxschmitt\Developer\playwright-vscode\node_modules\isexe\index.js:23:12)
at which2 (c:\Users\maxschmitt\Developer\playwright-vscode\node_modules\which\lib\index.js:63:24) …
```
=> chore: bump which dependency to v4

src/playwrightTest.ts, src/testModel.ts
https://github.com/microsoft/playwright/issues/29950
=> fix: error handling on list-files

src/testModel.ts
Reason: We rely on https://github.com/microsoft/playwright/pull/30677.
=> chore: use legacy driver in 1.43.0

.vscode/launch.json, package.json, src/extension.ts, src/settingsModel.ts, src/testModel.ts, tests/mock/vscode.ts, tests/utils.ts
Fixes https://github.com/microsoft/playwright/issues/30780
=> fix(state): use workspace state instead of the settings

src/playwrightTestServer.ts, src/playwrightTestTypes.ts, src/testModel.ts, src/upstream/testServerInterface.ts, tests/debug-tests.spec.ts, tests/mock/vscode.ts, tests/run-tests.spec.ts
Fixes https://github.com/microsoft/playwright/issues/30808
=> chore: fix debug stop and align config folder in test vs debug

package-lock.json, package.json, src/playwrightTestServer.ts
This also matches what we did in the meeting - but not with the title of the recent https://github.com/microsoft/playwright-vscode/pull/482 change.
Fixes https://github.com/microsoft/playwright/issues/30888
=> fix: debug on Windows

playwright.config.ts, src/playwrightTestCLI.ts, tests/debug-tests.spec.ts, tests/mock/vscode.ts
https://github.com/microsoft/playwright/issues/30829
https://github.com/microsoft/playwright/issues/30743
=> fix(debug): on legacy cli driver mode

src/extension.ts, src/playwrightTestServer.ts, src/testModel.ts, src/upstream/testServerConnection.ts, tests/debug-tests.spec.ts, tests/mock/vscode.ts
Fixes: https://github.com/microsoft/playwright/issues/30900
Fixes: https://github.com/microsoft/playwright/issues/30743
=> fix(debug): run global setup before debug

package.json
As per:
We get this since a while. We updated our minimum VSCode version to a recent one, so we should be save to remove that.
=> chore: remove pw.extension.install from 'activation events'

README.md, src/extension.ts
v1.38 is the minimum version which works as of today. This version got released on 14/09/2023.
=> chore: set minimum Playwright version to v1.38

src/extension.ts, src/traceViewer.ts
Fixes https://github.com/microsoft/playwright/issues/31314
=> bug(trace-viewer): update trace file on trace viewer when test completes

src/extension.ts, src/testModel.ts, src/traceViewer.ts, src/vscodeTypes.ts, tests/mock/vscode.ts, tests/spawn-trace-viewer.spec.ts, tests/utils.ts
Refactoring before introducing embedded mode.
- TraceViewer renamed to SpawnTraceViewer and moved into testModel (see https://github.com/microsoft/playwright-vscode/pull/483#discussion_r1661655108)
- TestModel is now disposable, to ensure all resources are properly released when extension is disposed
=> feat(trace-viewer): refactor trace viewer

playwright.config.ts, tests/mock/vscode.ts, tests/spawn-trace-viewer.spec.ts, tests/trace-viewer.spec.ts, tests/utils.ts
See https://github.com/microsoft/playwright-vscode/pull/513#discussion_r1706100779
=> test(trace-viewer): test harness for embedded trace viewer

package-lock.json, package.json, src/embeddedTraceViewer.ts, tests/embedded-trace-viewer.spec.ts
Related: https://github.com/microsoft/playwright/pull/32175
I'll leave it in draft because it requires that `@playwright/test` dependency to be updated to a version that includes https://github.com/microsoft/playwright/commit/b2ccfc3d01f8c1e228ec7af683115696fbf806fa
=> chore(trace-viewer): support source location external link

l10n/bundle.l10n.de.json, l10n/bundle.l10n.fr.json, l10n/bundle.l10n.json, l10n/bundle.l10n.zh-CN.json, package.json, package.nls.de.json, package.nls.fr.json, package.nls.json, package.nls.zh-CN.json, src/settingsModel.ts, src/settingsView.ts, src/testModel.ts, tests/mock/vscode.ts, tests/run-tests.spec.ts, tests/utils.ts
Closes https://github.com/microsoft/playwright/issues/32121.
Adds an opt-in checkbox called "Don't reuse global setup". When enabled, we'll re-run global setup before every test run.
=> feat: add toggle for always recreating global setup

src/installer.ts
Fixes https://github.com/microsoft/playwright/issues/32400
This will end up in an unused `--` when using Command Prompt. When using PowerShell, PowerShell will filter out the `--` and it will remove the quotes in both cases before sending it to NPM.
=> fix(windows): create Project via PowerShell Terminal

package-lock.json, package.json
This one already was on 1.47-alpha because of https://github.com/microsoft/playwright-vscode/pull/517
=> chore: bump @playwright/test to 1.47 beta

src/extension.ts, src/playwrightTestServer.ts, src/reporterServer.ts, src/testModel.ts, tests/debug-tests.spec.ts
Closes https://github.com/microsoft/playwright/issues/32387
We're using the cancellation token passed by VS Code to abort an ongoing debug run. There's two problems with this:
1. VS Code doesn't cancel the token if the debugger is terminated
1. If the debugger terminates during `runGlobalSetup`, the underlying process will go away and stall `runGlobalSetup`.
This PR fixes both by adding the debugger termination onto the cancellation token and racing `runGlobalSetup` against it.
=> fix: stop global setup when debugger is terminated

src/debugHighlight.ts, src/extension.ts, src/reusedBrowser.ts, src/settingsModel.ts, src/testModel.ts, tests/mock/vscode.ts
As a follow up to trace viewer changes, I did a poor man's leak analysis of disposables. I found some disposables left unhandled, mostly `EventEmitter`, so this PR is to fix them.
For the record, this is the script-as-test I did to catch those leaks (I didn't include it in this PR because it's just a best effort and not something we should rely on to catch leakages, but I can include it if you think it's worth it):
```js
import { expect, test } from './utils';
import * as vscodeTypes from '../src/vscodeTypes';
function isDisposable(o: any): o is vscodeTypes.Disposable {
return typeof o['dispose'] === 'function';
}
type VisitPath = [any, string[]];
function visit(obj: any, fn: (...o: VisitPath) => any) {
function innerVisit([obj, props]: VisitPath, visited = new Set()) {
if (obj === null …
```
=> chore: ensure disposables are disposed

package-lock.json, package.json, src/babelBundle.ts, src/babelHighlightUtil.ts, tests/highlight-locators.spec.ts
Fixes https://github.com/microsoft/playwright/issues/32619
=> chore: add @babel/plugin-proposal-decorators to babelBundle

src/extension.ts, src/playwrightTestServer.ts, src/reporterServer.ts, src/testModel.ts, tests/debug-tests.spec.ts
This reverts commit 4328be9555ecfe8a241e1ed3480e5e2b1866c9cf.
Relates https://github.com/microsoft/playwright/issues/32710
=> Revert "fix: stop global setup when debugger is terminated (#525)"

src/extension.ts, src/playwrightTestCLI.ts, src/playwrightTestServer.ts, src/reporterServer.ts, src/testModel.ts, tests/debug-tests.spec.ts
Second attempt at #525, which got reverted.
The problem was that we were stopping everything as soon as the first debug session stops. It turns out that there's more than one debug session though! The child process that's used to evaluate `playwright.config.ts` gets its own child debug session. Once it successfully closes, the `onDidTerminateDebugSession` handler is executed. In the past attempt, this closed debugging.
The fix is to only call `debugEnd.cancel()` if the main debug session is closed.
Closes https://github.com/microsoft/playwright/issues/32387
=> fix: stop global setup when debugger is terminated attempt #2

src/playwrightTestServer.ts, src/testModel.ts
Closes https://github.com/microsoft/playwright/issues/32959. Similar to the fix we shipped for debugging in #482 and #484.
=> fix: pass relative config path to test-server for running

src/playwrightTestServer.ts
This copies the hack from here to the new TestServer wiring:
https://github.com/microsoft/playwright-vscode/blob/fea6cfffcfce869b5193521651ba37af7b00b6e2/src/playwrightTestCLI.ts#L134
Fixes https://github.com/microsoft/playwright/issues/33209
=> fix: run Electron test

src/testModel.ts, tests/run-tests.spec.ts
Trace was disabled in #319 to solve https://github.com/microsoft/playwright/issues/21993.
Since then, two things happened:
- we do not clear output dir anymore;
- `tracesDir` is ignored when launching a reused browser over `connect()`.
Therefore, we do not need to disable tracing anymore, so might as well keep it.
Fixes https://github.com/microsoft/playwright/issues/33155.
=> fix: allow trace in showBrowser mode

package-lock.json, package.json
Release Notes:
- feat: add toggle for always recreating global setup #524
- fix(windows): create Project via PowerShell Terminal (#526)
- allow install command as terminal link provider (#528)
- fix: stop global setup when debugger is terminated (#537)
- chore: ensure disposables are disposed (#522)
- chore: add @babel/plugin-proposal-decorators to babelBundle (#532)
- fix(windows): pass relative config path to test-server for running (#538)
- fix: allow trace in showBrowser mode (#542)
=> chore: mark 1.1.11

src/terminalLinkProvider.ts
Sometimes we print commands inside a box:
```
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browser:               ║
║                                                                         ║
║     npx playwright install chromium-headless-shell                      ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
```
this was then not working correctly with the link highlighter which included the right box character. The new regex won't do that anymore.
=> fix: terminal link highlighter inside box

src/extension.ts, src/upstream/reporter.d.ts
This makes `Error.cause` render in test errors:
When looking at the Test Output tab, they are already getting shown, due to base reporter:
https://github.com/microsoft/playwright/issues/26848
=> chore: render Error.cause

tests/mock/vscode.ts
this caught my eye while working on https://github.com/microsoft/playwright-vscode/pull/551. The param is unused, i'm assuming it's a remnant from when we didn't have separate `run` and `watch` methods.
=> chore: remove unused param

src/extension.ts, tests/watch.spec.ts
Fixes https://github.com/microsoft/playwright/issues/33443.
When running a long test, or a test that times out, every file change leads to another "watch" run being enqueued. They all pile up in the command queue, and once blocking test finishes, they are all executed one-by-one. If the watched runs are all about the same file, then we'll see the same test being executed multiple times, once for each <kbd>⌘+S</kbd>. This is wasteful.
This PR fixes this by batching together all watched runs. We can't run watched files and watched IDs in the same test, so there's separate batches.
=> feat(watch): batch watch runs

src/ansi2html.ts, src/extension.ts, src/utils.ts, tests/run-tests.spec.ts
=> chore: fix ansi escaping for diffs

.azure-pipelines/publish.yml
The old one was Node.js 10 based.
=> chore: bump MicroBuildSigningPlugin to v4

package-lock.json, package.json, src/extension.ts, src/playwrightTestCLI.ts, src/playwrightTestServer.ts, src/testModel.ts
Fixes https://github.com/microsoft/playwright/issues/30815
Closes https://github.com/microsoft/playwright-vscode/pull/564
=> chore: reuse test run request

media/settingsView.css, src/settingsView.ts, tests/settings.spec.ts
Works towards https://github.com/microsoft/playwright/issues/33865. Once we have a "unselect all" button, we can automatically select all projects by default.
https://github.com/user-attachments/assets/e542a4d7-f71e-442c-bb15-5ed84b73f3b4
=> feat: Select all projects checkbox

src/utils.ts
close: https://github.com/microsoft/playwright/issues/33996
NVM lazy loading use cases such as the Oh My Zsh `nvm` plugin might make node a function which will be executed to set the node path when it is run, so executed the `node` command if it is a function to make it point to the real Node binary.
=> fix: node path detection for lazy loading

src/utils.ts
This is a follow-up to https://github.com/microsoft/playwright-vscode/pull/573 which avoids calling `grep` executable and uses shell string matching instead.
Reference https://github.com/microsoft/playwright/issues/33996
=> chore: use bash builtin string matching instead of calling grep

src/extension.ts, src/testModel.ts, tests/settings.spec.ts
We store settings like activated projects in `pw.workspace-settings`. But we only write to it if it's modified, which means that users who never change anything about them don't get their settings stored. If we ever change the default settings, this means their workflows + muscle memory will be broken. Not good!
To prevent that from happening, this PR makes us `saveSettings()` before every test run. It also adds some tests to cover that.
=> chore: running tests should create workspace-settings

.vscode/extensions.json, src/locatorsView.ts, src/settingsView.ts, src/utils.ts
=> chore: highlight HTML code

src/installer.ts
Closes https://github.com/microsoft/playwright/issues/34266. When we create the terminal, we don't know whether it's bash, Powershell, CMD or anything else. The VS Code API also doesn't give a good API to control that. So we need our `npm init` command to work under all three shells.
https://github.com/microsoft/playwright-vscode/pull/526 fixed a bug with NPM and Powershell, but regressed CMD:
Look at the bottom line: Under CMD, it incorrectly picks up `'--'` as the directory to create the project in.
I've played around with it, and found a command that's interpreted the same by all three shells:
*cmd*
*powershell*
*zsh*
=> fix: make create-playwright work under CMD

.eslintrc.js, src/debugHighlight.ts, src/extension.ts, src/installer.ts, src/playwrightTestCLI.ts, src/playwrightTestServer.ts, src/reporterServer.ts, src/testModel.ts, src/testTree.ts, src/utils.ts, src/workspaceObserver.ts, tests/debug-tests.spec.ts, tests/mock/vscode.ts, tests/problems.spec.ts
VSCode expects lowercase drive letter, while Playwright expects uppercase drive letter. This introduces bugs where we accidentally use two different casings for paths.
To achieve this and avoid future issues with path casing mismatch:
- make mock vscode lowercase the drive letter to match real vscode - this exposed a few tests that fail due to drive letter mismatch:
```
[default] › global-errors.spec.ts:19:5 › should report duplicate test title ────────────────────
[default] › list-tests.spec.ts:442:5 › should forget tests after error before first test ───────
[default] › problems.spec.ts:55:5 › should update diagnostics on file change ───────────────────
[default] › watch.spec.ts:24:5 › should watch all tests ────────────────────────────────────────
[default] › watch.spec.ts:147:5 › …
```
=> fix: ensure all paths use uppercase drive letter

src/extension.ts, tests/decorations.spec.ts
Closes https://github.com/microsoft/playwright/issues/34248
Updating decorations slows down the editor when the number of decorations is too high. We can work around it by limiting the number of decorations.
=> fix: limit decorations to prevent editor slowdown

src/backend.ts, src/playwrightTestServer.ts, src/reusedBrowser.ts
Ref https://github.com/microsoft/playwright/issues/30390
=> chore: add details on why test server failed to start

src/extension.ts
Follow-up to https://github.com/microsoft/playwright-vscode/pull/590.
Instead of capping the number of decorations per file, we now show at most one decoration per line. This still places a good upper limit so we don't overwhelm VS Code rendering with too many decorations. But it also prevents the confusing UI of decorations abruptly cutting off.
https://github.com/user-attachments/assets/3073f5bb-995b-436a-ac4d-de2c59c517c8
=> fix: show at most one decoration per line

package-lock.json, package.json, src/extension.ts, src/playwrightTestTypes.ts, src/testModel.ts, tests/mock/vscode.ts, tests/run-tests.spec.ts
Enables `pageSnapshot: 'only-on-failure'` for all test runs through the extension, and injects the page snapshot into the error message that Copilot uses to fix test failures.
related to https://github.com/microsoft/playwright/issues/34476
=> feat: provide page snapshot as context to copilot

src/playwrightTestCLI.ts, src/playwrightTestServer.ts, src/testModel.ts, src/utils.ts, tests/run-tests.spec.ts
Closes https://github.com/microsoft/playwright/issues/34813. When running the `foo` folder, we were sending `foo` over the wire instead of `foo/`. That meant that the `foobar/` folder also gets executed, which isn't expected.
The fix is to include the trailing slash in the locations we send to Playwright. Because Playwright interprets `/root/project/dir/` as a regular expression, I made it omit the leading slash for absolute directories. That has the same effect, because Playwright's location checker isn't strict.
=> fix: running a folder shouldn't also run folders that share prefix

src/backend.ts, src/reusedBrowser.ts, tests/utils.ts
VSCode's minimum Playwright version [is v1.38](https://github.com/microsoft/playwright-vscode/pull/487). These headers were removed in https://github.com/microsoft/playwright/pull/23215.
=> chore: remove x-playwright-debug-controller header

src/oopReporter.ts, src/upstream/teleEmitter.ts
This is a remnant from copying this over from the UI. `omitBuffers` is useful when sending from Node.js to the Browser, because the browser doesn't have a good representation of `Buffer`. In the extension, we're sending from Node to Node though, so we can turn this on.
One might think this leads to slightly more memory usage - but there was a bug where we were *already* spreading in the `body` field into the JSONified output, so I wouldn't worry.
=> chore: allow buffer attachments

media/common.css, src/settingsView.script.ts, src/settingsView.ts, tests/track-configs.spec.ts
Resolves https://github.com/microsoft/playwright/issues/35544
https://github.com/user-attachments/assets/b0b6ac89-9c26-4323-96f2-dd38f9254abc
=> fix: show config loading error

src/backend.ts, src/extension.ts, src/listTests.d.ts, src/playwrightTestTypes.ts, src/reusedBrowser.ts, src/testModel.ts, tests/pick-selector.spec.ts
This fixes two things:
a) `Pick Locator` command was launched before a `ReusableBrowser` was launched via a test. This now uses the first project's `'testIdAttribute'` for it.
b) 'Record at cursor' was not wired up correctly for `'testIdAttribute'`. This now uses also the project's use `'testIdAttribute'` instead of the one from the config.
Both were using a bad `'testIdAttribute'`:  Before when you had e.g. a `testIdAttribute` configured on `project1`, it was overridden again by `project2`.
Fixes https://github.com/microsoft/playwright/issues/35881
=> fix: move testIdAttributeName to config.use

src/playwrightTestServer.ts, src/upstream/teleEmitter.ts, src/upstream/teleReceiver.ts, tests/global-errors.spec.ts, tests/run-tests.spec.ts
This line was added as an unrelated change in https://github.com/microsoft/playwright-vscode/pull/478. It's printed on the first test run, but unconditionally. Users without plugins or global setup will still see it, and might be confused. I think it's better to leave it out - if the global setup file logs something, it'll be visible, otherwise it's fine to not see it.
=> chore: drop "Running global setup" line

src/extension.ts, src/playwrightTestServer.ts, src/reusedBrowser.ts, src/spawnTraceViewer.ts, src/testModel.ts, tests-integration/tests/baseTest.ts, tests/mock/vscode.ts, tests/pnp.spec.ts
I'm going through open source Playwright projects, and found a couple that use Yarn PnP or PNPM. I'd like to make sure that they work with the extension by default, but PnP currently doesn't. This PR implements the workaround from https://github.com/microsoft/playwright/issues/18931. PnP is complicated, so I'm expecting us to invite a ton of bugs with this. Let's take that complexity from our users and load it onto ourselves.
=> chore: yarn PnP support

src/reusedBrowser.ts
We got confused by this `Unconditionally close selector dialog, it might send inspect(enabled: false).` comment in the past. I dug up some history, but couldn't find any `inspect(enabled)` method on the debug controller. I've replaced the comment with what it actually does today, and added a minor refactor around where we show errors.
=> chore: refactor _startBackendIfNeeded
